title: Hong Chen # your name (or website title) here
logo: "/images/Prof_chen.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD in Human Informatics
  <br><br>
  Associate professor 
  <br><br>
  Daiichi Institute of Technology
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
